AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AutoSettled - AI-Powered Car Insurance Claims Processing

Globals:
  Function:
    Runtime: python3.10
    Timeout: 600
    MemorySize: 512
    Environment:
      Variables:
        S3_BUCKET_NAME: !Ref DocumentsBucket
        CUSTOMER_TABLE: !Ref CustomerTable
        POLICY_TABLE: !Ref PolicyTable
        VEHICLES_TABLE: !Ref VehiclesTable
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
    GatewayResponses:
      DEFAULT_4XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      DEFAULT_5XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"

Resources:
  # S3 Bucket for storing documents and images
  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub autosettled-documents-${AWS::AccountId}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedHeaders:
              - '*'
            MaxAge: 3000

  # DynamoDB Tables
  CustomerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: autosettled-customers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customer_id
          AttributeType: S
      KeySchema:
        - AttributeName: customer_id
          KeyType: HASH

  PolicyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: autosettled-policies
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: policy_id
          AttributeType: S
      KeySchema:
        - AttributeName: policy_id
          KeyType: HASH

  VehiclesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: autosettled-vehicles
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: vehicle_id
          AttributeType: S
      KeySchema:
        - AttributeName: vehicle_id
          KeyType: HASH

  ClaimsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: claims-records
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: claim_id
          AttributeType: S
      KeySchema:
        - AttributeName: claim_id
          KeyType: HASH

  # API Gateway Orchestration Lambda
  ApiOrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: autosettled-api-orchestrator
      Handler: api_orchestrator.lambda_handler
      CodeUri: ./lambda_functions/apiOrchestrator/
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref DocumentsBucket
          CLAIMS_TABLE: !Ref ClaimsTable
          BEDROCK_AGENT_ID: 8F18B4HMDE
          BEDROCK_AGENT_ALIAS_ID: TSTALIASID
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - "*"
          AllowHeaders:
            - "*"
          MaxAge: 300
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DocumentsBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ClaimsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeAgent
              Resource: '*'
      Events:
        InvokeAgent:
          Type: Api
          Properties:
            Path: /agent/invoke
            Method: POST
        StartClaim:
          Type: Api
          Properties:
            Path: /claim/start
            Method: POST
        GetClaim:
          Type: Api
          Properties:
            Path: /claim/{claimId}
            Method: GET
        ListClaims:
          Type: Api
          Properties:
            Path: /claims
            Method: GET

  # File Upload Lambda
  FileUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: autosettled-file-upload
      Handler: file_upload.lambda_handler
      CodeUri: ./lambda_functions/fileUpload/
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DocumentsBucket
      Events:
        Upload:
          Type: Api
          Properties:
            Path: /upload
            Method: POST

  # Customer Verification Lambda
  CustomerVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: autosettled-customer-verification
      Handler: lambda_function.lambda_handler
      CodeUri: ./lambda_functions/customerVerification/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CustomerTable
        - DynamoDBReadPolicy:
            TableName: !Ref PolicyTable
        - DynamoDBReadPolicy:
            TableName: !Ref VehiclesTable

  CustomerVerificationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CustomerVerificationFunction
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com

  # Policy Verification Lambda
  PolicyVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: autosettled-policy-verification
      Handler: lambda_function.lambda_handler
      CodeUri: ./lambda_functions/policyVerification/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PolicyTable
        - DynamoDBReadPolicy:
            TableName: !Ref VehiclesTable

  PolicyVerificationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PolicyVerificationFunction
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com

  # Damage Analysis Lambda
  DamageAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: autosettled-damage-analysis
      Handler: lambda_function.lambda_handler
      CodeUri: ./lambda_functions/analyzeDamageImages/
      Timeout: 900
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentsBucket
        - DynamoDBReadPolicy:
            TableName: !Ref VehiclesTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'

  DamageAnalysisPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DamageAnalysisFunction
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com

  # Document Analysis Lambda
  DocumentAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: autosettled-document-analysis
      Handler: lambda_function.lambda_handler
      CodeUri: ./lambda_functions/analyzeDocuments/
      Timeout: 900
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentsBucket
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - textract:*
              Resource: '*'

  DocumentAnalysisPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DocumentAnalysisFunction
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com

  # Settlement Decision Lambda
  SettlementDecisionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: autosettled-settlement-decision
      Handler: lambda_function.lambda_handler
      CodeUri: ./lambda_functions/generateSettlementDecision/
      Timeout: 900
      Layers:
        - arn:aws:lambda:us-east-1:986341371998:layer:pdf-generation-layer:2
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ClaimsTable
        - S3CrudPolicy:
            BucketName: !Ref DocumentsBucket
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'

  SettlementDecisionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SettlementDecisionFunction
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com

  # Frontend S3 Bucket
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub autosettled-frontend-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # CloudFront Origin Access Control
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub autosettled-frontend-oac-${AWS::AccountId}
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  # S3 Bucket Policy for CloudFront
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontendDistribution}

Outputs:
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  DocumentsBucketName:
    Description: "S3 Bucket for documents"
    Value: !Ref DocumentsBucket

  CustomerTableName:
    Description: "DynamoDB Customer Table"
    Value: !Ref CustomerTable

  PolicyTableName:
    Description: "DynamoDB Policy Table"
    Value: !Ref PolicyTable

  VehiclesTableName:
    Description: "DynamoDB Vehicles Table"
    Value: !Ref VehiclesTable

  ClaimsTableName:
    Description: "DynamoDB Claims Table"
    Value: !Ref ClaimsTable

  FrontendBucketName:
    Description: "S3 Bucket for Frontend"
    Value: !Ref FrontendBucket

  CloudFrontURL:
    Description: "CloudFront Distribution URL"
    Value: !GetAtt FrontendDistribution.DomainName

  CloudFrontDistributionId:
    Description: "CloudFront Distribution ID"
    Value: !Ref FrontendDistribution
